/*!
 * © 2019 Atypon Systems LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export { default as AddAuthorIcon } from './add-author'
export { default as AddCommentIcon } from './add-comment'
export { default as AddFigureIcon } from './add-figure'
export { default as AddedIcon } from './added'
export { default as AddNewIcon } from './add-new'
export { default as AddOutlineIcon } from './add-outline'
export { default as AddIcon } from './add'
export { default as AddRoleIcon } from './add-role'
export { default as ArrowDownIcon } from './arrow-down'
export { default as ArrowDownCircleIcon } from './arrow-down-circle'
export { default as ArrowLeftIcon } from './arrow-left'
export { default as ArrowUpIcon } from './arrow-up'
export { default as AttachIcon } from './attach'
export { default as AttentionBlueIcon } from './attention-blue'
export { default as AttentionGreenIcon } from './attention-green'
export { default as AttentionOrangeIcon } from './attention-orange'
export { default as AttentionRedIcon } from './attention-red'
export { default as AvatarIcon } from './avatar'
export { default as AlertIcon } from './alert'
export { default as AffiliationIcon } from './affiliation'
export { default as AuthorPlaceholderIcon } from './author-placeholder'
export { default as AffiliationPlaceholderIcon } from './affiliation-placeholder'
export { default as BookIcon } from './book'
export { default as ChatIcon } from './chat'
export { default as SystemUserAvatarIcon } from './system-user-avatar'
export { default as CitationCountIcon } from './citation-count'
export { default as CommentReplyIcon } from './comment-reply'
export { default as CommentResolveIcon } from './comment-resolve'
export { default as CommentIcon } from './comment'
export { default as CorrespondingAuthorIcon } from './corresponding-author'
export { default as DeleteSolidIcon } from './delete-solid'
export { default as DeleteIcon } from './deleted'
export { default as DotsIcon } from './dots'
export { default as DraggableIcon } from './draggable-icon'
export { default as EditIcon } from './edit'
export { default as EditAttrsTrackingIcon } from './edit-attrs-tracking'
export { default as FileAudioIcon } from './file-audio'
export { default as FileCodeIcon } from './file-code'
export { default as FileCompressedIcon } from './file-compressed'
export { default as FileCorruptedIcon } from './file-corrupted'
export { default as FileDocumentIcon } from './file-document'
export { default as FileFigureIcon } from './file-figure'
export { default as FileGraphicalAbstractIcon } from './file-graphical-abstract'
export { default as FileImageIcon } from './file-image'
export { default as FileLatexIcon } from './file-latex-icon'
export { default as FileMainDocumentIcon } from './file-main-document'
export { default as FilePdfIcon } from './file-pdf'
export { default as FileTableIcon } from './file-table'
export { default as FileUnknownIcon } from './file-unknown'
export { default as FileVideoIcon } from './file-video'
export { default as HandleInspectorIcon } from './handle-inspector'
export { default as HandleOutlineIcon } from './handle-outline'
export { default as HelpIcon } from './help'
export { default as ImageLeftIcon } from './image-left'
export { default as ImageDefaultIcon } from './image-default'
export { default as ImageRightIcon } from './image-right'
export { default as LinkIcon } from './link'
export { default as LockIcon } from './lock'
export { default as LogoutIcon } from './logout'
export { default as ManuscriptIcon } from './manuscript'
export { default as OutlineBlockQuoteIcon } from './outline-block-quote'
export { default as OutlineCodeIcon } from './outline-code'
export { default as OutlineEquationIcon } from './outline-equation'
export { default as OutlineEmbedIcon } from './outline-embed'
export { default as OutlineFigureIcon } from './outline-figure'
export { default as OutlineManuscriptIcon } from './outline-manuscript'
export { default as OutlineOrderedListIcon } from './outline-ordered-list'
export { default as OutlineParagraphIcon } from './outline-paragraph'
export { default as OutlinePullQuoteIcon } from './outline-pull-quote'
export { default as OutlineSectionIcon } from './outline-section'
export { default as OutlineTableIcon } from './outline-table'
export { default as OutlineUnorderedListIcon } from './outline-unordered-list'
export { default as PlusIcon } from './plus'
export { default as RoleAnnotatingIcon } from './role-annotating'
export { default as RoleReadingIcon } from './role-reading'
export { default as SaveStatusOfflineIcon } from './save-status-offline'
export { default as SaveStatusSavedIcon } from './save-status-saved'
export { default as SaveStatusSavingIcon } from './save-status-saving'
export { default as ScrollIcon } from './scroll'
export { default as SearchIcon } from './search'
export { default as SectionCategoryIcon } from './section-category'
export { default as SliderOffIcon } from './slider-off'
export { default as SliderOnIcon } from './slider-on'
export { default as TaskStepDoneIcon } from './task-step-done'
export { default as TickIcon } from './tick'
export { default as ToolbarBlockquoteIcon } from './toolbar-blockquote'
export { default as ToolbarBoldIcon } from './toolbar-bold'
export { default as ToolbarBoxedTextIcon } from './toolbar-boxed-text'
export { default as ToolbarCitationIcon } from './toolbar-citation'
export { default as ToolbarCodeIcon } from './toolbar-code'
export { default as ToolbarEquationIcon } from './toolbar-equation'
export { default as ToolbarFigureIcon } from './toolbar-figure'
export { default as ToolbarImageIcon } from './toolbar-image'
export { default as ToolbarItalicIcon } from './toolbar-italic'
export { default as ToolbarLinkIcon } from './toolbar-link'
export { default as ToolbarMediaIcon } from './toolbar-media'
export { default as ToolbarOrderedListIcon } from './toolbar-ordered-list'
export { default as ToolbarPullquoteIcon } from './toolbar-pullquote'
export { default as ToolbarSpecialCharactersIcon } from './toolbar-special-characters'
export { default as ToolbarSubscriptIcon } from './toolbar-subscript'
export { default as ToolbarSuperscriptIcon } from './toolbar-superscript'
export { default as ToolbarSymbolIcon } from './toolbar-symbol'
export { default as ToolbarTableIcon } from './toolbar-table'
export { default as ToolbarUnderlineIcon } from './toolbar-underline'
export { default as ToolbarUnorderedListIcon } from './toolbar-unordered-list'
export { default as ToolbarIndentIcon } from './toolbar-indent'
export { default as ToolbarUnindentIcon } from './toolbar-unindent'
export { default as TranslateIcon } from './translate'
export { default as TriangleCollapsedIcon } from './triangle-collapsed'
export { default as TriangleExpandedIcon } from './triangle-expanded'
export { default as UploadIcon } from './upload'
export { default as VerticalEllipsisIcon } from './vertical-ellipsis'
export { default as CrclTickAnimation } from './circle-tick-animation'
export { default as ProfileIcon } from './profile-avatar'
export { default as AddUserIcon } from './add-user'
export { default as AddInstitutionIcon } from './add-institution'
export { default as DangerIcon } from './danger'
